/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class CaAlunoEntradas extends javax.swing.JDialog {

    private Conexao c;
    private String Matricula;
    
    public CaAlunoEntradas(String Matricula) {
        initComponents();
        this.setModal(true);
        this.c = new Conexao();
        this.Matricula = Matricula;
        
        //Cadastrar
        if (Matricula.equals("0")) {
            this.setTitle("Cadastrar");
        }
        //Editar
        else {
            this.setTitle("Editar");
            
            //Carregar campos nos TextFields
            try {
                this.c.setResultSet("SELECT * FROM aluno WHERE Matricula = " + Matricula );
                if (this.c.getResultSet().first()) {
                      txtNome.setText(this.c.getResultSet().getString("Nome"));
                      txtCelular.setText(this.c.getResultSet().getString("Celular"));
                }
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblCelular.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencher o nome do aluno");
            txtNome.requestFocus();                    
        }
        else if (txtCelular.getText().equals("(  )     -    ")) {
            JOptionPane.showMessageDialog(this, "Preencher o celular do aluno");
            txtCelular.requestFocus();                    
        }
        else {   
            //Cadastrar
            if (this.Matricula.equals("0")) {
                c.SQLExecute("INSERT INTO aluno (Nome, Celular) "
                    + "VALUES ("
                    + "'" + txtNome.getText() + "', "
                    + "'" + txtCelular.getText() + "'"
                    + ")");
                JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso");
            }
            //Editar
            else {
                c.SQLExecute("UPDATE aluno SET "
                        + " Nome = '" + txtNome.getText() + "', "
                        + " Celular = '" + txtCelular.getText() + "' "
                        + " WHERE Matricula = " + this.Matricula
                );
                JOptionPane.showMessageDialog(this, "Aluno editado com sucesso");
            }
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblNome;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
